modLoader="javafml"
loaderVersion="[47,)" # for Forge 1.20.1
license="MIT"

[[mods]]
modId="dailymodunlocker"
version="1.0"
displayName="Daily Mod Unlocker"
description="Unlocks one mod per real-world day"
