modLoader="javafml"
loaderVersion="[47,)" # 対応Forgeバージョン範囲
license="MIT"

[[mods]]
modId="dailymodunlocker"
version="1.0.14"
displayName="Daily Mod Unlocker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/daily-mod-unlocker"
logoFile="logo.png" # 任意のロゴファイル
credits="Developed by Saizilyaku"
authors="Saizilyaku"
description="Unlocks one mod per real-world day. Includes optional support for mod addons."

[[mods.config]]
type="COMMON"
modId="dailymodunlocker"
fileName="dailymodunlocker-common.toml"
spec="com.example.dailymodunlocker.config.ModConfig::COMMON_SPEC"
